# This is a basic workflow to help you get started with Actions

name: Prelease

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: bump
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: production,sales
          pre_release_branches: main
          append_to_pre_release_tag: prerelease

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ steps.bump.outputs.previous_tag }}
          toTag: ${{ steps.bump.outputs.new_tag }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.bump.github_release.changelog }}
          tag_name: ${{ steps.bump.outputs.new_tag }}
          prerelease: true
